# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [3]:
import numpy as np
A = np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])
A


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [11]:
A = np.array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])
np.vstack(A)
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [25]:
A = np.arange(10).reshape(2,5)
B = np.arange(10, dtype = int).reshape(2,5)
print(A,B)
np.hstack((A,B))

[[0 1 2 3 4]
 [5 6 7 8 9]] [[0 1 2 3 4]
 [5 6 7 8 9]]


array([[0, 1, 2, 3, 4, 0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9, 5, 6, 7, 8, 9]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

In [ ]:
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# '''

In [2]:
import numpy as np
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
a.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Question:5

 How to Convert higher dimension into one dimension?

#### Desired Output::

In [3]:
import numpy as np
np.array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])
A = np.arange(15).reshape(1,3,5)
print(A.ndim, "dimensions")
print(A)
A = A.flatten()
print(A.ndim,  "dimension")
A

3 dimensions
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]]
1 dimension


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [4]:
import numpy as np
a = np.arange(15).reshape(-1,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [5]:
import numpy as np
A = np.random.randn(5,5)
np.square(A)

array([[4.55984482e-01, 2.93343681e+00, 2.02301676e-01, 1.12383336e+00,
        1.05785386e-02],
       [8.51589390e-01, 7.01266215e-01, 2.49997452e+00, 1.14654674e+00,
        1.57327448e-01],
       [6.13347846e-02, 1.59663369e+00, 1.28014055e-01, 1.73332634e-01,
        2.33203714e-01],
       [1.30330106e+00, 3.34265176e-01, 8.47063904e-02, 6.75691690e-02,
        2.33169007e-02],
       [1.57188008e-01, 4.40871849e-01, 3.19337176e-04, 9.96928467e-02,
        3.76095943e-02]])

## Question:8

### Create 5x6 an array and find the mean?

In [13]:
np.random.seed(100)
A = np.random.randint(30, size =(5,6))
print(A)
C = A.mean()
print(C)

[[ 8 24  3  7 23 15]
 [16 10 20  2 21  2]
 [ 2 14  2 17 16 24]
 [15  4 11 28 26 16]
 [27  9 29 22  2 27]]
14.733333333333333


## Question:9

### Find the standard deviation of the previous array in Q8?

In [14]:
np.std(C)

0.0

## Question:10

### Find the median of the previous array in Q8?

In [15]:
np.median(C)

14.733333333333333

## Question:11

### Find the transpose of the previous array in Q8?

In [17]:
print(A)
np.transpose(A)

[[ 8 24  3  7 23 15]
 [16 10 20  2 21  2]
 [ 2 14  2 17 16 24]
 [15  4 11 28 26 16]
 [27  9 29 22  2 27]]


array([[ 8, 16,  2, 15, 27],
       [24, 10, 14,  4,  9],
       [ 3, 20,  2, 11, 29],
       [ 7,  2, 17, 28, 22],
       [23, 21, 16, 26,  2],
       [15,  2, 24, 16, 27]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [20]:
A = np.arange(16).reshape(4,4)
print(A)
np.trace(A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


30

## Question:13

### Find the determinant of the previous array in Q12?

In [21]:
np.linalg.det(A)

0.0

## Question:14

### Find the 5th and 95th percentile of an array?

In [23]:
A = np.arange(10)
print(A)
print(np.percentile(A, 5))
print(np.percentile(A, 95))


[0 1 2 3 4 5 6 7 8 9]
0.45
8.549999999999999


## Question:15

### How to find if a given array has any null values?

In [26]:
A  = np.arange(10)
np.isnan(A)

array([False, False, False, False, False, False, False, False, False,
       False])